name: flutter_embed_unity
description: Harness the power of Unity 3D in your Flutter app by embedding Unity as a widget. Useful for adding 3D, gaming or augmented reality (AR) to your app.
version: 1.0.0
homepage: https://learntoflutter.com
repository: https://github.com/learntoflutter/flutter_embed_unity/tree/main/flutter_embed_unity
issue_tracker: https://github.com/learntoflutter/flutter_embed_unity/issues
documentation: https://github.com/learntoflutter/flutter_embed_unity/wiki
funding:
  - https://www.buymeacoffee.com/pPDtNs6A6T
topics:
  - unity

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_embed_unity_platform_interface: ^1.0.0
  flutter_embed_unity_2022_3_android: ^1.0.0
  flutter_embed_unity_2022_3_ios: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_embed_unity_2022_3_android
      ios:
        default_package: flutter_embed_unity_2022_3_ios
